### ISSUE TITLE
Telefon a PSČ nejsou u klientů validovány

### ISSUE THREAD

**Issue by Dangeboss** [ajeto007/mpr-project#12]
Ve formuláři pro přidání klienta se nekontroluje PSČ A TELEFON

**Kroky**
1. přihášení
2. Klienti/přidat klienta
3. vyplnění nesmyslného PSČ nebo Telefonu
4. odeslat

**Výsledek**
Klient je uložen

**Očekávaný výsledek**
Upozornění na nevalidní položky

**Comment by Spilky** [comment]
@house2332 a je to vůbec třeba? Je to systém pro interní použití, takže když si tam zadají špatné hodnoty, tak prostě jejich blbost.

**Comment by VojtechBuba** [comment]
Z pohledu uživatelské přívětivosti by tam validace být měla. Co se týče konzistence dat, tak by to bylo taky dobré to tam mít. Ja osobně bych tomu dal menší prioritu a vrátil se k tomu až budou dodělané zásadnější věci typu matice, nástěnka, kontrola oprávnění atd.

**Comment by Spilky** [comment]
@Dangeboss jak se to povedlo dát nevalidní telefon, když tam jsou ty input masky?

**Comment by Dangeboss** [comment]
@Spilky chovalo se to tak, že tam byly zobrazené podtržítka  a mohl jsem si dát například 7__ ___ __1. Teď už se to chová správně.
