### ISSUE TITLE
Smazání zaměsnance, který je přiřazený do projektu - 500 err

### ISSUE THREAD

**Issue by Dangeboss** [ajeto007/mpr-project#13]
Snažím se smazat zaměstnance, který je přiřazený k nějakému projektu.

**Kroky**
1. přihlášení
2. smazání zaměstnance, který je přiřazený k projektu

**Výsledek**
500 err

**Očekávaný výsledek**
Upozornění

**Comment by Spilky** [comment]
@Dangeboss šlo o vedoucího projektu, zobrazil jsem hlášku, že se nesmí smazat vedoucí projektu. Zaměstnanec, který není v žádném projektu vedoucí smazat jde.

**Comment by Dangeboss** [comment]
Restest OK
