### ISSUE TITLE
Editace uživatele - 500 error

### ISSUE THREAD

**Issue by Dangeboss** [ajeto007/mpr-project#2]
Editace přihlášeného uživatele generuje výjimku

**Kroky:**
1. přihlášení
2. kliknutí nahoře vpravo na profil
3. změna jména
4. kliknutí na odeslat

**Očekávaný výsledek:**
Jméno uživatele se přepíše

**Výsledek**:
500 server error

Upravovaný uživatel: kalus.jiri@gmail.com

**Comment by vokracko** [comment]
Bude souviset s rolí z #6

**Comment by Spilky** [comment]
@Dangeboss zkus to a kdyžtak znovu otevři issue.

**Comment by Dangeboss** [comment]
Stejné chování. Editovaný uživatel: kalus.jiri@gmail.com. Zkoušel jsem, jestli to není datumem (změnili jste formát), ale není.

**Comment by Dangeboss** [comment]
...

**Comment by Dangeboss** [comment]
Retest OK
