### ISSUE TITLE
Přidat zaměstnance - nevalidní PSČ

### ISSUE THREAD

**Issue by Dangeboss** [ajeto007/mpr-project#3]
PSČ je povinné, ale není validované.

**Kroky:**
1. Přihlášení
2. Firma/Přidat zaměstnance
3. Vyplnění PSČ písmeny (např. "aa")
4. Kliknutí na odeslat

**Očekávaný výsledek:**
Upozornění na nevalidní PSČ

**Výsledek:**
Uživatel se vytvoří

**Comment by Dangeboss** [comment]
U klienta to ještě není validované

**Comment by vokracko** [comment]
Klient patri do #12

**Comment by Dangeboss** [comment]
Retest zaměstnance OK
