### ISSUE TITLE
Ikona datepickeru při nepovedeném odeslání zmizí

### ISSUE THREAD

**Issue by Dangeboss** [ajeto007/mpr-project#4]
Kliknu na odeslat při špatně vyplněném formuláři. Jsem upozorněn na povinná pole, přičemž ikona datepickeru zmizí. 

**Kroky:**
1. Přihlášení
2. Firma/Přidat zaměstnance
3. Nevyplnění aspoň jedné povinné položky
4. Kliknutí na odeslat

**Očekávaný výsledek:**
Ikona datepickeru nezmizí.

**Výsledek:**
Ikona datepickeru zmizela.

Update: 
1.stejné chování i u formuláře "Upravit zaměstnance". 
2. stačí kliknout na ikonu kalendáře a po zadání data ikona zmizí

**Comment by phaljuk** [comment]
Vyřešeno 5741f763e2c71326b72f0057734913732512f662

**Comment by Dangeboss** [comment]
Retest OK
