### ISSUE TITLE
Zadání datumu narození - nejde se pohybovat šipkami

### ISSUE THREAD

**Issue by Dangeboss** [ajeto007/mpr-project#5]
Naklikám si datum a pak chci pohnout kurzorem a přepsal třeba den. 

**Kroky:**
1. Přihlášení
2. Firma/Přidat zaměstnance
3. Vyplnění datumu narození
4. Editace datumu narození

**Očekávaný výsledek:**
Kurzor se hýbe mezi chary.

**Výsledek:**
Kurzor stojí na místě. Občas se pohne o jeden symbol :)

**Comment by lucidvoci** [comment]
@Dangeboss No, tahle chyba se deje i na oficialnich strankach datepickeru [tady](http://eonasdan.github.io/bootstrap-datetimepicker/). Tohle nevim presne, jak opravit.

**Comment by Spilky** [comment]
@Dangeboss @lucidvoci tak na to kašlem, prostě to bude fungovat tak, jak to funguje

**Comment by Dangeboss** [comment]
OK
