### ISSUE TITLE
Upravit zaměstnance s jinou rolí než vedoucí

### ISSUE THREAD

**Issue by Dangeboss** [ajeto007/mpr-project#6]
Pokud chci upravit zaměstnance s jinou rolí než je vedoucí, tak dostanu 500 err. V detailu vidím, že se role nepřiřadila.

**Kroky:**
1. přihlášení
2. Přehled zaměstnanců
3. Editace zaměstnance s rolí jinou než vedoucí

**Očekávaný výsledek:**
Zobrazí se formulář pro výsledek

**Výsledek:**
500 error

**Comment by vokracko** [comment]
Mě to jede.
@Spilky tipl bych že se nepřepsala db, u sebe jsem musel smazat a znovu vygenerovat celou tabulku aby se projevila změna hodnot enumu.

**Comment by Spilky** [comment]
@vokracko Pravda, zapomněl jsem v DB upravit ten enum.

**Comment by Spilky** [comment]
@Dangeboss Můžeš zkusit znova, už by to mělo být v klidu.

**Comment by Dangeboss** [comment]
@Spilky Teď už mi nejde editovat ani zaměstnanec, který je vedoucí.

**Comment by Spilky** [comment]
@Dangeboss jo to je způsobené oravou toho, že to již hlásí, že e-mail existuje, používá se tam stejný formulář pro přidání a editaci a zapomněl jsem to ošetřit. Odpoledne vyřeším.

**Comment by Dangeboss** [comment]
Retest OK
