### ISSUE TITLE
Přehled kategorií - 500 err

### ISSUE THREAD

**Issue by Dangeboss** [ajeto007/mpr-project#7]
Přidal jsem rizika s různými kategoriemi a potom klikl na přehled kategorií. Nemusí to být tím. Radši se podívej do logu na výjimku. Čas: 25.04.2016 cca 9:00

**Kroky:**
1. přihlášení
2. Rizika/Kategorie

**Očekávaný výsledek:**
Tabulka s kategoriemi

**Výsledek:**
500 error

**Comment by Spilky** [comment]
@Dangeboss Tohle mi budeš muset popsat asi víc, nedaří se mi to nasimulovat.

**Comment by Spilky** [comment]
@Dangeboss už jsem na to přišel a mělo by to být opravené.

**Comment by Dangeboss** [comment]
@Spilky  pořád to padá. Přidal jsem jen zaměstnance a pak klik na Kategorie. To by souvislost mít nemělo. Možná mi to zkus přepnout do debug módu. Ještě mě napadlo, jestli máme stejný stav db.

**Comment by Spilky** [comment]
@Dangeboss on si ten současný stav datagridu uložil do session, aby se ti to po najetí zobrazovalo stejně, bohužel si ale amatuje chybný DB dotaz, takže to háže chybu. Vypnu to ukládání stavu do session a mělo by to být v poho.

**Comment by Dangeboss** [comment]
@Spilky  Restest OK
