### ISSUE TITLE
Datepicker - záporná doba projektu

### ISSUE THREAD

**Issue by Dangeboss** [ajeto007/mpr-project#9]
Projekt může skončit dřív než začal

**Kroky:**
1. přihlášení
2. Projekty/Vytvořit projekt
3. datum začátku : 4.5.2016, datum konce 3.5 2016
4. odeslat

**Výsledek:**
Projekt se uloží

**Očekávaný výsledek:**
Upozornění, neuložení projektu

**Comment by Spilky** [comment]
@lucidvoci prosím zajistit opravu na straně datepickeru

**Comment by Spilky** [comment]
@Petrod  prosím zajistit opravu na straně zpracování formuláře v nette

**Comment by lucidvoci** [comment]
@Spilky oprava na strane datepickeru
